### PR TITLE
Add extra environment to onMessage

### LINKED ISSUE #70: Enhance onMessage for Sharding.start
Would be useful to have the definition for 

```scala 
onMessage: Msg => ZIO[Entity[State], Nothing, Unit]
```
 in `Sharding.start` to accept more environment, and provide it from outside like 
```
Sharding.start(...).provideLayer(layerForOnMessage)`
```

### PR DESCRIPTION
**Pull request by octavz**
This adds support to pass extra environment to the  `onMessage` callback that is passed to the `Sharding.start`

Closes https://github.com/zio/zio-akka-cluster/issues/70

This is breaking change since `Entity[State]` is passed as a layer and not as a trait anymore, I don't know if is the best solution but was the fastest I could find.

PS This is my first PR in ZIO, I have no clue what I am supposed to be doing

### CODE REVIEW

**Review by ghostdogpr — COMMENTED** [review]
This looks very good! Can you also update the README so that it reflects the changes? Thanks!

Also a small tip, if you write `Closes #70` or `Fixes #70` in the description, the issue will be automatically closed when this PR is merged, which is always nice 😄

**Comment by octavz** [comment]
I modified code examples in README, I am not sure I should add anything more, please let me know, ty.

**Comment by octavz** [comment]
Most of the tests are based on waiting on promises, I think there should be a timeout, otherwise, in case something goes wrong these tests eat half an hour of CI resources for no reason.

**Review by ghostdogpr — APPROVED** [review]
LGTM. I’ll try merge and do a release tomorrow 👍

**Comment by ghostdogpr** [comment]
There’s a new ZIO release coming so I’ll wait for it until I merge and release this, if that’s okay with you.

**Pull request merged**
