### PR TITLE
#8: Added Scala 2.13; 2.12.8 -> 2.12.10

### PR DESCRIPTION
**Pull request by soujiro32167**

### CODE REVIEW

**Review by ghostdogpr — APPROVED** [review]
Looks good, thanks!

**Comment by ghostdogpr** [comment]
@soujiro32167 do you need a release with 2.13? Let me know and I'll do it, otherwise I just wait for the next ZIO release.

**Comment by soujiro32167** [comment]
hey @ghostdogpr ! It would be nice to have a 2.13 release. There are no particular features I need from there, but I wanted to try and implement distributed sorting using zio-akka-cluster

**Comment by ghostdogpr** [comment]
Ok I’ll get it done tomorrow 👍

**Comment by ghostdogpr** [comment]
@soujiro32167 there was a little issue that I fixed (it was publishing only for 2.13 and not for 2.12 anymore). It's now published for both!

**Pull request merged**
